lanuage: minimal
sudo: false
ignore:
  - examples/*
env:
  - GOARCH=amd64
notifications:
  email:
    on_success: change
    on_failure: always

sudo: required

services:
  - docker

script: make && make release

after_success:
  - ./scripts/ci/tag.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true