name: CI
on: [push]
jobs:

  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    name: fmt, lint, test
    env:
      ENVIRONMENT: ci
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run fmt & lint
        run: make generate && make fmt && make lint

      - name: Run tests
        run: make generate && make test

  build:
    name: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      ENV: ci
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run build
      run: make generate && make test && make build

    - name: run tag export
      run: ./scripts/ci/tag.sh