name: Check
on: [push]
jobs:

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    env:
      ENV: ci
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run fmt
      run: make fmt

  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      ENV: ci
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run lint
      run: make lint

  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      ENV: ci
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run tests
      run: make test

  build:
    name: build
    runs-on: ubuntu-latest
    env:
      ENV: ci
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run build
      run: make build